# Generated by Django 3.1.4 on 2021-09-16 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210914_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Chatting images')),
                ('file', models.FileField(blank=True, null=True, upload_to='Chatting files')),
                ('read', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=False)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sender', to='accounts.profile')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='accounts.profile')),
            ],
            options={
                'ordering': ['Date'],
            },
        ),
    ]
