# Generated by Django 3.1.4 on 2021-09-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_group_group_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Searching_Name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
