# Generated by Django 3.1.4 on 2021-09-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='topic',
            field=models.CharField(choices=[('Technology', 'Technology'), ('handmade', 'handmade'), ('software development', 'software development'), ('Cars', 'Cars'), ('Business', 'Business'), ('Freelancing', 'Freelancing'), ('Animals', 'Animals')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='interest',
            field=models.CharField(choices=[('Technology', 'Technology'), ('handmade', 'handmade'), ('software development', 'software development'), ('Cars', 'Cars'), ('Business', 'Business'), ('Freelancing', 'Freelancing'), ('Animals', 'Animals')], max_length=50),
        ),
    ]
