# Generated by Django 3.1.4 on 2021-09-18 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210918_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Gender',
        ),
    ]
