# Generated by Django 3.1.4 on 2021-09-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chatters',
            field=models.ManyToManyField(blank=True, related_name='chats', to='accounts.profile'),
        ),
    ]
