# Generated by Django 3.1.4 on 2021-09-26 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210926_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_message',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='g_msgs', to='accounts.group_message'),
        ),
    ]
