# Generated by Django 3.1.4 on 2021-09-27 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20210927_0406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_message',
            name='readers',
        ),
        migrations.AddField(
            model_name='group_message',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
