# Generated by Django 3.1.4 on 2021-09-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210927_0511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_message',
            name='sent',
        ),
        migrations.AddField(
            model_name='group_message',
            name='readers',
            field=models.ManyToManyField(blank=True, related_name='readers', to='accounts.profile'),
        ),
    ]
